### ISSUE TITLE
fab deployment fails on linux mint 17

### ISSUE THREAD

**Issue by quintusdias** [quintusdias/sams#12]
seems to fail when building scipy, which is needed by seaborn.  

```
[jevans@jevans-linux] out: Installing collected packages: scipy, nose, pyparsing, pytz, python-dateutil, six, seaborn, pandas, matplotlib, numpy, Django
[jevans@jevans-linux] out:   Running setup.py install for scipy
[jevans@jevans-linux] out:     Traceback (most recent call last):
[jevans@jevans-linux] out:       File "<string>", line 1, in <module>
[jevans@jevans-linux] out:       File "/tmp/pip-build-v1lcae60/scipy/setup.py", line 249, in <module>
[jevans@jevans-linux] out:         setup_package()
[jevans@jevans-linux] out:       File "/tmp/pip-build-v1lcae60/scipy/setup.py", line 237, in setup_package
[jevans@jevans-linux] out:         from numpy.distutils.core import setup
[jevans@jevans-linux] out:     ImportError: No module named 'numpy'
[jevans@jevans-linux] out:     Complete output from command /home/jevans/samssite/jevans-linux/virtualenv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-v1lcae60/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xh490zdb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jevans/samssite/jevans-linux/virtualenv/include/site/python3.4:
[jevans@jevans-linux] out:     Traceback (most recent call last):
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:       File "<string>", line 1, in <module>
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:       File "/tmp/pip-build-v1lcae60/scipy/setup.py", line 249, in <module>
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:         setup_package()
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:       File "/tmp/pip-build-v1lcae60/scipy/setup.py", line 237, in setup_package
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:         from numpy.distutils.core import setup
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:     ImportError: No module named 'numpy'
[jevans@jevans-linux] out:     
[jevans@jevans-linux] out:     ----------------------------------------
[jevans@jevans-linux] out:     Command "/home/jevans/samssite/jevans-linux/virtualenv/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-v1lcae60/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-xh490zdb-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jevans/samssite/jevans-linux/virtualenv/include/site/python3.4" failed with error code 1 in /tmp/pip-build-v1lcae60/scipy
```

Succeeds when installing the requirements packages manually, though.

**Comment by quintusdias** [comment]
fixed with commit 823e514
